#!/usr/bin/env python3
# coding: utf-8
"""
runner.py — Skill Recommender

Given a prompt, finds the most similar training examples in the accumulated
scoring matrix and recommends skills (and the fitness metrics they were best
measured by) that performed well on similar inputs.

Usage
-----
    # Single inline query
    python runner.py "How do I reset my SmartHub device?"

    # Read query from stdin
    echo "Explain invoice payment terms" | python runner.py -

    # Batch: one query per line from a file
    python runner.py --from-file queries.txt

    # List all skills in the matrix (no query needed)
    python runner.py --list-skills

    # Cache the fitted TF-IDF embedder so repeated queries skip re-fitting
    python runner.py "some prompt" --cache-embedder /tmp/embedder.pkl
    python runner.py "another prompt" --cache-embedder /tmp/embedder.pkl  # instant load

    # Run as a module (equivalent to python runner.py)
    python -m skill_recommender "some prompt"

    # Full options
    python runner.py "some prompt" \\
        --data-dir ~/.openjiuwen/oracle \\
        --variant  baseline \\        # baseline | evolved | both
        --embedder tfidf \\           # tfidf | openai
        --sim-threshold  0.25 \\      # min cosine similarity to include an example
        --score-threshold 0.20 \\     # min weighted score to show a result
        --min-examples 1 \\           # min similar examples required
        --top-k 10 \\                 # max results shown per query
        --cache-embedder ~/.openjiuwen/oracle/embedder.pkl

Prerequisites
-------------
    1. Run gepa_scoring_matrix mode at least once with oracle_data_dir set in
       config.json so that scoring_matrix_*.json files are accumulated.
    2. The JSON files must contain baseline_cross_eval / evolved_cross_eval
       sections (generated by the current step_matrix_run_gepa.py).
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

# ── path bootstrap so we can run as a script ──────────────────────────────────
_HERE = Path(__file__).resolve().parent
_PROJECT_ROOT = _HERE.parent.parent.parent.parent.parent  # michael-agent-core/
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

from examples.agent_evolving_hermes.offline.offline_05_thompson_vs_baseline.skill_recommender.recommender import (  # noqa: E402
    build_recommender,
    SkillRecommender,
)

DEFAULT_ORACLE_DIR = Path("~/.openjiuwen/oracle").expanduser()
SEP  = "─" * 70
SEP2 = "═" * 70


# ── Output helpers ────────────────────────────────────────────────────────────

def _print_results(results: list[dict], query: str, variant: str) -> None:
    print(f"\n{SEP2}")
    print(f"  Skill Recommender  [{variant}]")
    print(f"  Query  : {query[:120]}")
    print(SEP2)

    if not results:
        print("  No recommendations above the configured thresholds.")
        print(SEP2)
        return

    for i, r in enumerate(results, 1):
        print(f"\n  [{i}] Skill  : {r['skill']}")
        print(f"       Metric : {r['metric']}")
        print(f"       Score  : {r['score']:.3f}  "
              f"(mean_sim={r['mean_similarity']:.3f}, "
              f"{r['n_examples']} similar example(s))")
        for ex in r["similar_examples"]:
            sim = ex["similarity"]
            inp = ex.get("input", "")
            out = ex.get("output", "")
            exp = ex.get("expected", "")
            print(f"       ↳ [{sim:.3f}] prompt  : {inp}")
            if exp:
                print(f"                expected : {exp}")
            if out:
                print(f"                output   : {out}")

    print(f"\n{SEP}")


def _print_skills(rec: SkillRecommender) -> None:
    print(f"\n{SEP2}")
    print("  Skills in the matrix")
    print(SEP2)
    print(f"  Total rows : {rec.n_examples}")
    print(f"  Metrics    : {rec.metrics}")
    print()
    for skill in rec.skills:
        n = int((rec._df["skill_name"] == skill).sum())
        print(f"  {skill:<40s}  {n:>4} example(s)")
    print(SEP)


# ── Main ─────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(
        prog="runner.py",
        description="Recommend skills for a given prompt using the scoring matrix.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    # ── Positional / mutually exclusive input modes ──────────────────────
    input_group = parser.add_mutually_exclusive_group()
    input_group.add_argument(
        "query",
        nargs="?",
        default=None,
        help="Prompt to find skills for.  Pass '-' to read from stdin.",
    )
    input_group.add_argument(
        "--from-file",
        metavar="PATH",
        type=Path,
        default=None,
        help="File with one query per line; results are printed for each.",
    )
    input_group.add_argument(
        "--list-skills",
        action="store_true",
        default=False,
        help="List all skills in the matrix and exit (no query needed).",
    )

    # ── Matrix / model settings ──────────────────────────────────────────
    parser.add_argument(
        "--data-dir",
        metavar="PATH",
        type=Path,
        default=DEFAULT_ORACLE_DIR,
        help="Directory with scoring_matrix_*.json files  [default: ~/.openjiuwen/oracle]",
    )
    parser.add_argument(
        "--variant",
        choices=["baseline", "evolved", "both"],
        default="baseline",
        help="Which layer of the 3-D matrix to use  [default: baseline]",
    )
    parser.add_argument(
        "--embedder",
        choices=["tfidf", "openai"],
        default="tfidf",
        help="Embedding backend  [default: tfidf]",
    )

    # ── Recommendation thresholds ────────────────────────────────────────
    parser.add_argument(
        "--sim-threshold",
        type=float,
        default=0.25,
        metavar="FLOAT",
        help="Min cosine similarity to include an example  [default: 0.25]",
    )
    parser.add_argument(
        "--score-threshold",
        type=float,
        default=0.20,
        metavar="FLOAT",
        help="Min weighted normalised score to return a result  [default: 0.20]",
    )
    parser.add_argument(
        "--min-examples",
        type=int,
        default=1,
        metavar="N",
        help="Min number of similar examples required to recommend  [default: 1]",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=10,
        metavar="N",
        help="Max results per query  [default: 10]",
    )
    parser.add_argument(
        "--cache-embedder",
        metavar="PATH",
        type=Path,
        default=None,
        help="Path to cache the fitted embedder (loaded if exists, saved otherwise).",
    )

    args = parser.parse_args()

    # ── Build recommender (shared across all queries) ─────────────────────
    oracle_dir   = args.data_dir.expanduser()
    cache_path   = Path(args.cache_embedder).expanduser() if args.cache_embedder else None

    try:
        rec = build_recommender(
            oracle_dir      = oracle_dir,
            variant         = args.variant,
            embedder_method = args.embedder,
        )
    except FileNotFoundError as exc:
        sys.exit(
            f"[ERROR] {exc}\n\n"
            "Run gepa_scoring_matrix mode first with oracle_data_dir configured."
        )
    except ValueError as exc:
        sys.exit(
            f"[ERROR] {exc}\n\n"
            "The scoring_matrix_*.json files may predate baseline_cross_eval support.\n"
            "Re-run gepa_scoring_matrix to regenerate them."
        )

    # ── Embedder cache ────────────────────────────────────────────────────
    if cache_path is not None:
        from .embedder import Embedder
        if cache_path.exists():
            try:
                rec._embedder = Embedder.load(cache_path)
                print(f"  Embedder cache   : loaded from {cache_path}")
            except Exception as exc:
                print(f"  [WARN] Could not load embedder cache ({exc}); using fresh model.")
        else:
            rec._embedder.save(cache_path)
            print(f"  Embedder cache   : saved to {cache_path}")

    print(f"  Loaded matrix: {rec.n_examples} rows · {len(rec.skills)} skill(s) · "
          f"{len(rec.metrics)} metric(s)")

    # ── --list-skills mode ────────────────────────────────────────────────
    if args.list_skills:
        _print_skills(rec)
        return

    # ── Resolve queries ───────────────────────────────────────────────────
    if args.from_file is not None:
        fp = Path(args.from_file).expanduser()
        if not fp.exists():
            sys.exit(f"[ERROR] File not found: {fp}")
        queries = [line.strip() for line in fp.read_text(encoding="utf-8").splitlines()
                   if line.strip()]
        if not queries:
            sys.exit(f"[ERROR] File is empty: {fp}")
    elif args.query is None or args.query == "-":
        if sys.stdin.isatty():
            print("Enter your query (press Enter then Ctrl-D to submit):")
        raw = sys.stdin.read().strip()
        if not raw:
            parser.error("Query is empty.  Provide a prompt as argument, --from-file, or via stdin.")
        queries = [raw]
    else:
        queries = [args.query.strip()]

    # ── Run recommendations ───────────────────────────────────────────────
    for query in queries:
        if not query:
            continue
        results = rec.recommend(
            query           = query,
            sim_threshold   = args.sim_threshold,
            score_threshold = args.score_threshold,
            min_examples    = args.min_examples,
            top_k           = args.top_k,
        )
        _print_results(results, query, args.variant)


if __name__ == "__main__":
    main()
